### ISSUE TITLE
Error 500

### ISSUE THREAD

**Issue by bokub** [Atinux/coffee-or-tea#1]
FYI: 

![image](https://github.com/Atinux/vue-london-edge/assets/17952318/fb3bb7f7-49cb-4011-89ac-cd840c84256a)

**Comment by atinux** [comment]
Thank you, fixed in https://github.com/Atinux/vue-london-edge/commit/126d1987dc0dd3b12cc606180b719cad5ba3972f

Though to live code on stage 😄 

It's live! https://vue-london.pages.dev/
